### POST request to add data in db
POST http://localhost:8080/maps/save
Content-Type: application/json

{
  "zoom": 10,
  "center1": 45.0,
  "center2": -0.08,
  "country": "France"
}

### GET data on the country
GET http://localhost:8080/maps/France
Content-Type: application/json

### DELETE data on the country
DELETE http://localhost:8080/maps/France
Content-Type: application/json
