
spring:
    application:
        name: GeoFind
    datasource:
        url: jdbc:mysql://localhost:3306/geofind
        username: geofind
        password: geofind
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
    mail:
        host: smtp.sendgrid.net
        port: 587
        username: apikey
        #password: ${SENDGRID_API_KEY}   # clé depuis variable d'environnement
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.connectiontimeout: 5000
            mail.smtp.timeout: 5000
            mail.smtp.writetimeout: 5000

logging:
    level:
        org.flywaydb: DEBUG
