
server:
    port: ${PORT:8080}
spring:
    application:
        name: GeoFind
    datasource:
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
    mail:
        host: smtp.sendgrid.net
        port: 587
        username: apikey
        password: ${SENDGRID_API_KEY}   # clé depuis variable d'environnement
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.connectiontimeout: 5000
            mail.smtp.timeout: 5000
            mail.smtp.writetimeout: 5000

logging:
    level:
        org.flywaydb: info
