
spring:
    application:
        name: GeoFind
    datasource:
        url: jdbc:mysql://localhost:3306/geofind
        username: geofind
        password: geofind
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration

logging:
    level:
        org.flywaydb: DEBUG
